const VIDEOS = {
    "anasayfa": [
        "e6k7-uhkQ5o",
        "vJvXmfyiW6c",
        "wvO1Hra6Ba0",
        "Dvxts3Bd91E",
        "roY3-hYz7hM",   
     ],
    "dugun": [
        "gHaIwJd6rAE",
        "OakHCFmpRa4",
    ],
    "nostalji": [
        "at0Z9oZo1Qo",
        "M_XNnOx1Z-w",
        "WBHg4Sc2A98",
        "qu7QQUdKfwc",
        "tPlZNEDJURE",
        "aWKln4Vcgbs",
        "O-LU74LZiuQ",
        "cAY8ex4S7zY",
        "oXMW8SZha-s",
        "1w8PDQ4tuEg",
        "IEmAHlX6KHc",
        "1GNPAfQToHk",
        "Wa5p-xumohk",
        "UA9d-t2ntDU",
        "KofQASq2aPQ",
        "ZcHv4GyG4no",
        "ihR8_unPjBE",
        "M0xxa-46MTY",
        "KhsUjig3WKk",
        "HIkG-aHwfi4",
        "_tBEgjdOGns",
    ],
    "videolar": [
        "OqdmgxSATQ0",
    ],
    "klipler": [
        "j20fHNQiFEk",
        "Ve_JzcqtWqU",
        "AmeNBneGibQ",
        "RfgQW32WDlg",
        "QFSNf68eNjs",
        "NSjU-0gDRUc",
        "xXC9LLIonow",
        "9ZfLUpsqra8",
        "gTjzUujMni4",
    ]
}
